# Config file for training a classifier on two tasks : digit classification and background classification.
# The base encoder was trained with simCLR on views that shared background features only.

# ImageNet info
imagenet_data_folder: "/home/kind_boyd/workdir/data_td3/subset_imagenet"
imagenet_labels_file: "/home/kind_boyd/workdir/data_td3/imagenet_labels.txt"
imagenet_classes: [2, 3, 4, 6, 43, 203, 400, 600, 700, 800]

# MNIST info
mnist_data_folder: "/home/kind_boyd/workdir/data_td3/mnist"

# Model info
d_model: 128

# Data info
shared_feature: background
data_mean: [0.485, 0.456, 0.406]
data_std: [0.229, 0.224, 0.225]
device: 'cuda'

# Training info
n_neighbors: 3
batch_size: 64

# Results folder
res_dir: "/home/kind_boyd/workdir/DL4IA/docs/tutorials/learning_visual_representations/pretrained/contrastive_background/dummy"

