# Config file for a random search in hyperparameter space.

data_folder:
labels_file:

subset_classes: [2, 3, 4, 6, 43, 203, 400, 600, 700, 800]
data_mean: [0.485, 0.456, 0.406]
data_std: [0.229, 0.224, 0.225]
size: 224
d_model: 128

epochs: 20
batch_size: 8
lr_min: 0.0001
lr_max: 0.1
temperature_min: 0.01
temperature_max: 10
n_trials: 10

device: 'cuda'
transforms:
  - cropping
  - resize
  - color_distortion
  - gaussian_blur
  - normalize
crop_size: 128
kernel_size: 11

pretrained_params:

res_dir:
